/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.example;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        Triangle tr = new Triangle(3.0, 4.0, 5.0);
        System.out.println(tr.getArea());

        System.out.printf("Side 1: %.2f%n", tr.getX());
        System.out.printf("Side 2: %.2f%n", tr.getY());
        System.out.printf("Side 3: %.2f%n", tr.getZ());

        System.out.println(tr.isEquilateral());
        System.out.println(tr.isIsosceles());
        System.out.println(tr.isScalene());
        System.out.println(tr.isTriangle());
    }
}
